import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {createServer} from 'node:net';import pg from 'pg';
import {localDatabase} from '../scripts/bootstrap.js';import {poolFor,tx,assertRuntimeRole} from '../server/db.js';import {createApp} from '../server/app.js';import {totp} from '../server/security.js';import {sample} from './fixtures.js';import {capture,captureLedger,restoreSnapshot,type Snapshot} from '../scripts/snapshot.js';import {migrate} from '../scripts/migrate.js';import {pruneExpired} from '../scripts/retention.js';import {randomUUID} from 'node:crypto';
async function freePort(){const s=createServer();await new Promise<void>(r=>s.listen(0,'127.0.0.1',r));const n=(s.address() as {port:number}).port;await new Promise<void>(r=>s.close(()=>r()));return n;}
test('phase 2: real PostgreSQL persistence, RLS and end-to-end APIs',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'renzhen-test-'));const local=await localDatabase(dir,await freePort(),true);const pool=poolFor(local.config);await assertRuntimeRole(pool);const server=createApp(pool,local.config).listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));const base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 type Client={cookie?:string;csrf?:string};const a:Client={},b:Client={},admin:Client={};
 async function api(client:Client,url:string,method='GET',body?:unknown,headers:Record<string,string>={}){const res=await fetch(base+url,{method,headers:{origin:local.config.origin,'content-type':'application/json',...(client.cookie?{cookie:client.cookie}:{}),...(client.csrf?{'x-csrf-token':client.csrf}:{}),...headers},body:body===undefined?undefined:JSON.stringify(body)});const cookie=res.headers.get('set-cookie');if(cookie)client.cookie=cookie.split(';')[0];const data=await res.json();if(data.csrf)client.csrf=data.csrf;return {status:res.status,data};}
 const enrollment={adult:true,privacy:true,sensitive:true,privacyVersion:local.config.privacyVersion,sensitiveVersion:local.config.sensitiveVersion,mockAcknowledged:true};let recovery='',idA='',idB='',version1='',matchId='';let snapshot:Snapshot;let poolClosed=false;
 try{
  await t.test('adult and independent consents are required, admin authorization enforced',async()=>{for(const consent of ['adult','privacy','sensitive'])assert.equal((await api({},'/api/enroll','POST',{...enrollment,[consent]:false})).status,400);assert.equal((await api({},'/api/enroll','POST',{...enrollment,mockAcknowledged:false})).status,400);assert.equal((await api({},'/api/admin/users')).status,401);assert.equal((await api({},'/api/enroll','POST',enrollment,{origin:'https://attacker.invalid'})).status,403);const enrolled=await api(a,'/api/enroll','POST',enrollment);assert.equal(enrolled.status,201);recovery=enrolled.data.recovery;assert.ok(recovery.length>=40);assert.equal((await api(b,'/api/enroll','POST',enrollment)).status,201);idA=(await api(a,'/api/me')).data.user.id;idB=(await api(b,'/api/me')).data.user.id;});
  await t.test('auto-save is revision checked, branch answers cleaned, CSRF enforced',async()=>{assert.equal((await api(a,'/api/answers','PUT',{answers:sample,revision:0},{'x-csrf-token':'wrong'})).status,403);const r=await api(a,'/api/answers','PUT',{answers:{...sample,pet_kind:'狗'},revision:0});assert.equal(r.status,200);assert.equal(r.data.revision,1);assert.equal((await api(a,'/api/answers','PUT',{answers:sample,revision:0})).status,409);const me=(await api(a,'/api/me')).data;assert.equal(me.answers.pet_kind,undefined);version1=me.response.version_id;});
  await t.test('complete submissions persist, duplicate submission is idempotent',async()=>{const body={answers:sample,revision:1,contact:null,contactConsent:false,confirm:true,privacyVersion:local.config.privacyVersion,sensitiveVersion:local.config.sensitiveVersion,mockAcknowledged:true};const first=await api(a,'/api/submit','POST',body);assert.equal(first.status,200);assert.match(first.data.publicId,/^RR-/);const again=await api(a,'/api/submit','POST',body);assert.equal(again.data.publicId,first.data.publicId);assert.equal(again.data.duplicate,true);assert.equal((await api(b,'/api/submit','POST',{...body,revision:0,answers:{...sample,gender:'男性',seeking:['女性']}})).status,200);});
  await t.test('database RLS isolates identities and returns no leaked rows on connection reuse',async()=>{await tx(pool,'user',idA,async db=>{assert.equal((await db.query('SELECT id FROM rr.users WHERE id=$1',[idB])).rowCount,0);assert.equal((await db.query('SELECT user_id FROM rr.response_answers WHERE user_id=$1',[idB])).rowCount,0);await assert.rejects(db.query('INSERT INTO rr.user_contacts(user_id,ciphertext) VALUES($1,$2)',[idB,'forbidden']));});await tx(pool,'user',undefined,async db=>assert.equal((await db.query('SELECT id FROM rr.users')).rowCount,0));assert.equal((await api(a,`/api/me/${idB}`)).status,404);assert.equal((await api(a,'/api/admin/users')).status,401);const owner=new pg.Pool({connectionString:local.migrationUrl});await assert.rejects(assertRuntimeRole(owner));const ciphertext=(await owner.query('SELECT ciphertext FROM rr.response_answers LIMIT 1')).rows[0].ciphertext;assert.ok(!ciphertext.includes('女性'));await owner.end();});
  await t.test('admin password + TOTP, replay blocked, audited sensitive access',async()=>{const otp=totp(local.state.totp,Math.floor(Date.now()/30000));const body={username:'local-admin',password:local.state.adminPassword,otp};assert.equal((await api(admin,'/api/admin/login','POST',body)).status,200);assert.equal((await api({},'/api/admin/login','POST',body)).status,401);const detail=await api(admin,`/api/admin/users/${idA}`);assert.equal(detail.data.answers.age,28);assert.equal((await api(admin,'/api/admin/users')).data.users.length,2);});
  await t.test('new version publication preserves old answers and database rejects old version edits',async()=>{const v=(await api(admin,'/api/admin/versions','POST',{from:version1})).data;const qs=(await api(admin,`/api/admin/versions/${v.id}`)).data.questions;qs[0].title='请填写你的周岁年龄';assert.equal((await api(admin,`/api/admin/versions/${v.id}`,'PUT',{questions:qs})).status,200);assert.equal((await api(admin,`/api/admin/versions/${v.id}/publish`,'POST',{})).status,200);assert.equal((await api(a,'/api/me')).data.response.version_id,version1);assert.equal((await api(admin,`/api/admin/versions/${version1}`,'PUT',{questions:qs})).status,409);await tx(pool,'admin',undefined,async db=>assert.rejects(db.query("UPDATE rr.questions SET definition='{}' WHERE version_id=$1",[version1])));});
  await t.test('manual candidates require explicit administrator authorization even after both users agree',async()=>{
   const suggestions=(await api(admin,'/api/admin/suggestions')).data;assert.equal(suggestions.mode,'manual');assert.deepEqual(suggestions.suggestions,[]);assert.equal((await api(admin,'/api/admin/weights','PUT',{})).status,503);
   const result=await api(admin,'/api/admin/matches','POST',{a:idA,b:idB,save:true});assert.equal(result.data.report.mode,'manual');assert.equal(result.data.report.score,null);assert.deepEqual(result.data.report.dimensions,[]);matchId=result.data.id;
   const approval={decision:'authorize',confirmedManually:true,basicConditionsReviewed:true};
   assert.equal((await api({},`/api/admin/matches/${matchId}/authorization`,'POST',approval)).status,401);
   assert.equal((await api(admin,`/api/admin/matches/${matchId}/authorization`,'POST',{...approval,confirmedManually:false})).status,400);
   assert.equal((await api(admin,`/api/admin/matches/${matchId}/authorization`,'POST',approval)).status,409);
   for(const id of [idA,idB]){await api(admin,`/api/admin/users/${id}`,'PATCH',{matchingStatus:'reviewed'});assert.equal((await api(admin,`/api/admin/matches/${matchId}/feedback`,'PUT',{userId:id,decision:'yes',confirmedExternally:true})).status,200);}
   let saved=(await api(admin,'/api/admin/matches')).data.matches[0];assert.equal(saved.canIntroduce,false);assert.equal(saved.authorization_status,'pending');assert.equal(saved.score,null);
   assert.equal((await api(admin,`/api/admin/matches/${matchId}/authorization`,'POST',approval,{'x-csrf-token':'wrong'})).status,403);
   assert.equal((await api(admin,`/api/admin/matches/${matchId}/authorization`,'POST',approval)).status,200);
   saved=(await api(admin,'/api/admin/matches')).data.matches[0];assert.equal(saved.canIntroduce,true);assert.equal(saved.authorization_status,'authorized');assert.ok(saved.authorized_by);assert.ok(saved.authorized_at);
   const logs=(await api(admin,'/api/admin/audit')).data.logs;assert.ok(logs.some((x:{action:string;admin_id:string})=>x.action==='matching.authorize'&&x.admin_id===saved.authorized_by));
   assert.equal((await api(admin,`/api/admin/matches/${matchId}/authorization`,'POST',{...approval,decision:'reject'})).status,200);assert.equal((await api(admin,'/api/admin/matches')).data.matches[0].canIntroduce,false);
   assert.equal((await api(admin,`/api/admin/matches/${matchId}/authorization`,'POST',approval)).status,200);
   await api(admin,`/api/admin/matches/${matchId}/feedback`,'PUT',{userId:idA,decision:'no',confirmedExternally:true});saved=(await api(admin,'/api/admin/matches')).data.matches[0];assert.equal(saved.canIntroduce,false);assert.equal(saved.authorization_status,'rejected');assert.equal(saved.authorized_by,null);
   assert.equal((await api(admin,`/api/admin/matches/${matchId}/authorization`,'POST',approval)).status,409);assert.equal((await api(admin,'/api/admin/matches','POST',{a:idA,b:idB,save:false})).data.report.eligible,false);
  });
  await t.test('match authorization requires recent administrator MFA',async()=>{const owner=new pg.Pool({connectionString:local.migrationUrl});try{await owner.query("UPDATE rr.sessions SET mfa_at=now()-interval '11 minutes' WHERE kind='admin'");assert.equal((await api(admin,`/api/admin/matches/${matchId}/authorization`,'POST',{decision:'authorize',confirmedManually:true,basicConditionsReviewed:true})).status,403);}finally{await owner.query("UPDATE rr.sessions SET mfa_at=now() WHERE kind='admin'");await owner.end();}});
  await t.test('mock and real modes cannot share user authentication or candidate matching',async()=>{local.config.mock=false;try{assert.equal((await api(a,'/api/me')).status,401);assert.equal((await api({},'/api/recover','POST',{recovery})).status,401);assert.equal((await api(admin,'/api/admin/suggestions')).data.suggestions.length,0);assert.equal((await api(admin,'/api/admin/matches','POST',{a:idA,b:idB,save:false})).data.report.eligible,false);}finally{local.config.mock=true;}});
  await t.test('snapshot captures encrypted persistent records',async()=>{const owner=new pg.Pool({connectionString:local.migrationUrl});try{snapshot=await capture(owner);assert.equal(snapshot.tables.users.length,2);assert.ok(snapshot.tables.response_answers.every(x=>String(x.ciphertext).startsWith('v1.')));}finally{await owner.end();}});
  await t.test('secure recovery, rotation, modification clears matching consent, withdrawal and deletion',async()=>{const oldCookie=a.cookie;assert.equal((await api(a,'/api/recover','POST',{recovery})).status,200);assert.equal((await api({cookie:oldCookie},'/api/me')).status,401);assert.equal((await api(a,'/api/reopen','POST',{})).status,200);assert.equal((await api(admin,'/api/admin/matches')).data.matches.length,0);const rotated=(await api(a,'/api/recovery/rotate','POST',{})).data.recovery;assert.equal((await api({},'/api/recover','POST',{recovery})).status,401);assert.equal((await api(a,'/api/withdraw','POST',{confirm:true})).status,200);assert.equal((await api(a,'/api/me')).data.user.status,'withdrawn');assert.equal((await api(a,'/api/answers','PUT',{answers:sample,revision:0})).status,409);assert.equal((await api(a,'/api/me','DELETE',{confirm:true})).status,200);assert.equal((await api({},'/api/recover','POST',{recovery:rotated})).status,401);const logs=(await api(admin,'/api/admin/audit')).data.logs;assert.ok(logs.some((x:{action:string})=>x.action==='sensitive.answers.read'));assert.ok(logs.some((x:{action:string})=>x.action==='user.delete'));assert.ok(!JSON.stringify(logs).includes('女性'));assert.ok(!JSON.stringify(logs).includes(recovery));});
  await t.test('isolated restore replays deletion ledger and revokes old sessions',async()=>{const owner=new pg.Pool({connectionString:local.migrationUrl});await owner.query('CREATE DATABASE restore_test');const restoreAddress=new URL(local.migrationUrl);restoreAddress.pathname='/restore_test';const restoredUrl=restoreAddress.href;await migrate(restoredUrl);const restored=new pg.Pool({connectionString:restoredUrl});try{const ledger=await captureLedger(owner);const legacy=structuredClone(snapshot!);for(const match of legacy.tables.matching_results){delete match.authorization_status;delete match.authorized_by;delete match.authorized_at;match.score=90;}await restoreSnapshot(restored,legacy,ledger,local.config.tokenKey);assert.equal((await restored.query('SELECT id FROM rr.users WHERE id=$1',[idA])).rowCount,0);assert.equal((await restored.query('SELECT id FROM rr.users WHERE id=$1',[idB])).rowCount,1);assert.equal((await restored.query('SELECT token_hash FROM rr.sessions')).rowCount,0);assert.equal((await restored.query('SELECT accepting FROM rr.questionnaires')).rows[0].accepting,false);}finally{await restored.end();await owner.query('DROP DATABASE restore_test');await owner.end();}});
  await t.test('pause blocks open enrollment and AI stays off',async()=>{assert.equal((await api(admin,'/api/admin/questionnaire/state','POST',{accepting:false})).status,200);assert.equal((await api({},'/api/enroll','POST',enrollment)).status,409);assert.equal((await api(admin,'/api/admin/ai/analyze','POST',{})).status,503);assert.equal((await api(admin,'/api/admin/export','POST',{includeContacts:false,purpose:'manual_review'})).status,200);});
  await t.test('maintenance retention deletes only expired data and records a tombstone',async()=>{const owner=new pg.Pool({connectionString:local.migrationUrl});const expired=randomUUID();await owner.query("INSERT INTO rr.users(id,recovery_hash,mock,expires_at) VALUES($1,$2,true,now()-interval '1 day')",[expired,randomUUID()]);assert.equal(await pruneExpired(pool,local.config),1);assert.equal((await owner.query('SELECT id FROM rr.users WHERE id=$1',[idB])).rowCount,1);assert.equal((await owner.query("SELECT 1 FROM rr.audit_logs WHERE action='retention.delete'")).rowCount,1);await owner.end();});
  await t.test('admin audit is append only and login endpoint is rate limited',async()=>{await tx(pool,'admin',undefined,async db=>assert.rejects(db.query("DELETE FROM rr.audit_logs WHERE action='admin.login'")));let rateLimited=false;for(let i=0;i<5;i++){const r=await api({},'/api/admin/login','POST',{username:'local-admin',password:'deliberately-wrong-local-password',otp:'000000'});if(r.status===429)rateLimited=true;}assert.equal(rateLimited,true);});
 await pool.end();poolClosed=true;
  await t.test('persistent records survive PostgreSQL stop and restart',async()=>{const check=new pg.Pool({connectionString:local.migrationUrl});const before=(await check.query('SELECT id FROM rr.users ORDER BY id')).rows;await check.end();await local.postgres.stop();await local.postgres.start();const reopened=new pg.Pool({connectionString:local.migrationUrl});try{assert.deepEqual((await reopened.query('SELECT id FROM rr.users ORDER BY id')).rows,before);}finally{await reopened.end();}});
 }finally{await new Promise<void>(r=>server.close(()=>r()));if(!poolClosed)await pool.end();await local.postgres.stop();await rm(dir,{recursive:true,force:true});}
});
