import {test} from 'node:test';import assert from 'node:assert/strict';import {analyzePair,defaultWeights} from '../shared/matching.js';import {defaultQuestions,cleanAnswers,validateQuestionnaire} from '../shared/model.js';import {hashPassword,verifyPassword,seal,unseal,newTotpSecret,totp,verifyTotp} from '../server/security.js';
import {sample} from './fixtures.js';
const a={id:'a',active:true,answers:sample},b={id:'b',active:true,answers:{...sample,gender:'男性',seeking:['女性']}};
test('phase 1: deterministic reciprocal eligibility and configurable scoring',()=>{const r=analyzePair(a,b);assert.equal(r.eligible,true);assert.equal(r.score,100);assert.deepEqual(r,analyzePair(a,b));assert.equal(analyzePair(b,a).score,r.score);assert.ok(r.caveat.includes('不代表恋爱成功概率'));const altered={...b,answers:{...b.answers,values_honesty:1}};assert.ok(analyzePair(a,altered).score!<100);assert.equal(analyzePair(a,altered,{...defaultWeights,values:0}).score,100);});
test('hard conditions never produce a score',()=>{for(const answers of [{...b.answers,age:17},{...b.answers,seeking:['男性']},{...b.answers,age_min:30},{...b.answers,relationship:'仍在探索'},{...b.answers,match_accept:'暂时不愿意'}]){const r=analyzePair(a,{...b,answers});assert.equal(r.eligible,false);assert.equal(r.score,null);}assert.equal(analyzePair(a,b,defaultWeights,true).eligible,false);assert.equal(analyzePair(a,{...b,active:false}).eligible,false);assert.equal(analyzePair(a,a).eligible,false);});
test('missing dimensions do not inflate the result',()=>{const {values_honesty,...missing}=b.answers;assert.equal(analyzePair(a,{...b,answers:missing}).score,null);});
test('question validation rejects incompatible edits and strips hidden branch answers',()=>{validateQuestionnaire(defaultQuestions);assert.throws(()=>validateQuestionnaire(defaultQuestions.filter(x=>x.key!=='age')));const clean=cleanAnswers(defaultQuestions,{...sample,pet_kind:'狗',unrecognized:'ignored'},true);assert.equal(clean.pet_kind,undefined);assert.equal(clean.unrecognized,undefined);assert.throws(()=>cleanAnswers(defaultQuestions,{...sample,age:16},true));assert.throws(()=>cleanAnswers(defaultQuestions,{...sample,age_min:40},true));});
test('encryption authenticates context, password hash and TOTP replay prevention',async()=>{const k='a'.repeat(64);const encrypted=seal(sample,k,'a');assert.deepEqual(unseal(encrypted,k,'a'),sample);assert.throws(()=>unseal(encrypted,k,'b'));const password=await hashPassword('long-local-test-password');assert.equal(await verifyPassword('long-local-test-password',password),true);assert.equal(await verifyPassword('wrong',password),false);const secret=newTotpSecret(),n=Math.floor(Date.now()/30000),code=totp(secret,n);assert.equal(verifyTotp(secret,code,-1),n);assert.equal(verifyTotp(secret,code,n),null);});

import {readConfig} from '../server/config.js';
test('production and real-data modes require explicit verified configuration',()=>{const env={...process.env};try{Object.assign(process.env,{DATABASE_URL:'postgresql://rr_runtime:local-only@localhost/postgres',DATA_ENCRYPTION_KEY:'a'.repeat(64),TOKEN_HASH_KEY:'b'.repeat(64),APP_ORIGIN:'https://test.invalid',NODE_ENV:'development',DATA_MODE:'real',LAUNCH_APPROVED:'false'});assert.throws(()=>readConfig(),/approval/);process.env.LAUNCH_APPROVED='true';assert.throws(()=>readConfig(),/document versions/);Object.assign(process.env,{PRIVACY_VERSION:'verified-1',SENSITIVE_VERSION:'verified-1',PROCESSOR_NAME:'fictional-test-processor',PRIVACY_CONTACT:'fictional-test-contact',NODE_ENV:'production',DATABASE_SSL:'false',DATABASE_CA_PEM:'test-only-not-valid-ca'});assert.throws(()=>readConfig(),/TLS/);process.env.DATABASE_SSL='true';assert.equal(readConfig().mock,false);process.env.APP_ORIGIN='http://localhost:8080';assert.throws(()=>readConfig(),/HTTPS/);process.env.APP_ORIGIN='https://test.invalid';process.env.TOKEN_HASH_KEY=process.env.DATA_ENCRYPTION_KEY;assert.throws(()=>readConfig(),/Independent/);}finally{for(const key of Object.keys(process.env))if(!(key in env))delete process.env[key];Object.assign(process.env,env);}});
