import express,{type Request,type Response,type NextFunction} from 'express';
import helmet from 'helmet';import {z} from 'zod';import {randomUUID} from 'node:crypto';import path from 'node:path';
import type {Config} from './config.js';import {tx,type DB,type SQL} from './db.js';
import {token,digest,seal,unseal,verifyPassword,verifyTotp} from './security.js';
import {answersSchema,questionSchema,validateQuestionnaire,cleanAnswers,type Answers,type Question} from '../shared/model.js';
import {defaultWeights,type Profile} from '../shared/matching.js';
import {manualReport} from './manual-matching.js';
class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
const fail=(status:number,message:string):never=>{throw new HttpError(status,message);};
type Session={token_hash:string;kind:'user'|'admin';user_id:string|null;admin_id:string|null;csrf_hash:string;csrf_ciphertext:string;mfa_at:Date|null};
type Authed=Request&{session?:Session;requestId?:string};
const uuid=z.string().uuid();
const contactSchema=z.object({channel:z.enum(['微信','手机','邮箱']),value:z.string().trim().min(3).max(120)}).strict().nullable();
export function createApp(pool:DB,c:Config){
 const app=express();app.disable('x-powered-by');app.set('trust proxy',c.trustProxy);
 app.use(helmet({contentSecurityPolicy:{directives:{defaultSrc:["'self'"],scriptSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],imgSrc:["'self'","data:"],connectSrc:["'self'"],fontSrc:["'self'"],frameAncestors:["'none'"]}},strictTransportSecurity:c.production?{maxAge:31536000,includeSubDomains:true}:false}));
 app.use(express.json({limit:'128kb'}));
 app.use((req:Authed,res,next)=>{req.requestId=randomUUID();res.setHeader('X-Request-Id',req.requestId);res.setHeader('Cache-Control','no-store');if(req.path.startsWith('/api')&&['POST','PUT','PATCH','DELETE'].includes(req.method)){if(req.get('origin')!==c.origin)return next(new HttpError(403,'请求来源无效'));if(!req.is('application/json'))return next(new HttpError(415,'需要 JSON 请求'));}next();});
 const wrap=(fn:(req:Authed,res:Response)=>Promise<unknown>)=>(req:Request,res:Response,next:NextFunction)=>{Promise.resolve(fn(req as Authed,res)).catch(next);};
 async function audit(db:SQL,req:Authed,action:string,target?:string){await db.query('INSERT INTO rr.audit_logs(admin_id,action,target_hash,request_id) VALUES($1,$2,$3,$4)',[req.session?.admin_id||null,action,target?digest(target,c.tokenKey):null,req.requestId]);}
 async function rate(req:Request,bucket:string,limit:number,seconds=600,extra=''){const key=digest(`${bucket}:${bucket==='admin-account'?'account':req.ip}:${extra}`,c.tokenKey);const hits=await tx(pool,'auth',undefined,async db=>(await db.query("INSERT INTO rr.rate_limits(key,hits,window_end) VALUES($1,1,now()+$2*interval '1 second') ON CONFLICT(key) DO UPDATE SET hits=CASE WHEN rr.rate_limits.window_end<now() THEN 1 ELSE rr.rate_limits.hits+1 END,window_end=CASE WHEN rr.rate_limits.window_end<now() THEN EXCLUDED.window_end ELSE rr.rate_limits.window_end END RETURNING hits",[key,seconds])).rows[0].hits);if(hits>limit)fail(429,'操作过于频繁，请稍后再试');}
 const cookieName=(kind:'user'|'admin')=>c.production?`__Secure-rr_${kind}`:`rr_${kind}`;
 const cookie=(res:Response,kind:'user'|'admin',value:string)=>res.cookie(cookieName(kind),value,{httpOnly:true,secure:c.production,sameSite:'strict',path:'/api',maxAge:(kind==='admin'?8:24)*3600000});
 const clear=(res:Response,kind:'user'|'admin')=>res.clearCookie(cookieName(kind),{httpOnly:true,secure:c.production,sameSite:'strict',path:'/api'});
 const requireAuth=(kind:'user'|'admin',recent=false)=>(req:Request,_res:Response,next:NextFunction)=>{authenticate(req as Authed,kind,recent).then(()=>next()).catch(next);};
 async function authenticate(req:Authed,kind:'user'|'admin',recent:boolean){
  const raw=req.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName(kind)+'='))?.slice(cookieName(kind).length+1);
  if(!raw||raw.length>100)fail(401,'请恢复填写或重新登录');
  const s=await tx(pool,'auth',undefined,async db=>(await db.query("SELECT s.* FROM rr.sessions s LEFT JOIN rr.users u ON u.id=s.user_id LEFT JOIN rr.admin_users a ON a.id=s.admin_id WHERE s.token_hash=$1 AND s.kind=$2 AND s.expires_at>now() AND ((s.kind='user' AND u.expires_at>now() AND u.mock=$3) OR (s.kind='admin' AND a.active))",[digest(raw!,c.tokenKey),kind,c.mock])).rows[0] as Session|undefined);
  if(!s)fail(401,'会话已过期，请使用恢复凭证或重新登录');
  if(['POST','PUT','PATCH','DELETE'].includes(req.method)&&digest(req.get('x-csrf-token')||'',c.tokenKey)!==s!.csrf_hash)fail(403,'安全校验未通过，请刷新页面');
  if(recent&&(!s!.mfa_at||Date.now()-new Date(s!.mfa_at).getTime()>600000))fail(403,'敏感操作需要重新验证动态验证码');req.session=s;
 }
 async function session(db:SQL,kind:'user'|'admin',id:string){const raw=token(),csrf=token(),hash=digest(raw,c.tokenKey);await db.query("INSERT INTO rr.sessions(token_hash,kind,user_id,admin_id,csrf_hash,csrf_ciphertext,expires_at,mfa_at) VALUES($1,$2,$3,$4,$5,$6,now()+$7*interval '1 hour',$8)",[hash,kind,kind==='user'?id:null,kind==='admin'?id:null,digest(csrf,c.tokenKey),seal(csrf,c.encryptionKey,hash),kind==='admin'?8:24,kind==='admin'?new Date():null]);return {raw,csrf};}
 async function questions(db:SQL,version:string):Promise<Question[]>{return (await db.query('SELECT definition FROM rr.questions WHERE version_id=$1 ORDER BY position',[version])).rows.map(x=>x.definition);}
 async function loadResponse(db:SQL,userId:string){const r=(await db.query('SELECT * FROM rr.responses WHERE user_id=$1',[userId])).rows[0];if(!r)fail(404,'没有可填写的问卷');const rows=(await db.query('SELECT question_key,ciphertext FROM rr.response_answers WHERE response_id=$1',[r.id])).rows;const answers:Answers={};for(const x of rows)answers[x.question_key]=unseal(x.ciphertext,c.encryptionKey,`${userId}:${r.id}:${x.question_key}`);return {response:r,answers,questions:await questions(db,r.version_id)};}
 async function writeAnswers(db:SQL,userId:string,responseId:string,answers:Answers){await db.query('DELETE FROM rr.response_answers WHERE response_id=$1',[responseId]);for(const [key,value] of Object.entries(answers))await db.query('INSERT INTO rr.response_answers(response_id,user_id,question_key,ciphertext) VALUES($1,$2,$3,$4)',[responseId,userId,key,seal(value,c.encryptionKey,`${userId}:${responseId}:${key}`)]);}
 app.get('/api/health',wrap(async(_req,res)=>{await pool.query('SELECT 1');res.json({ok:true});}));
 app.get('/api/meta',wrap(async(_req,res)=>{const state=await tx(pool,'auth',undefined,async db=>(await db.query('SELECT title,accepting,current_version_id FROM rr.questionnaires ORDER BY id LIMIT 1')).rows[0]);res.json({name:'认真认识',mock:c.mock,approved:c.approved,retentionDays:c.retentionDays,privacyVersion:c.privacyVersion,sensitiveVersion:c.sensitiveVersion,processorName:c.processorName,privacyContact:c.privacyContact,accepting:!!state?.accepting,hasPublished:!!state?.current_version_id,aiEnabled:false,matchingMode:'manual',icpRecord:c.icpRecord||null});}));
 app.post('/api/enroll',wrap(async(req,res)=>{
  await rate(req,'enroll',50,3600);
  const body=z.object({adult:z.literal(true),privacy:z.literal(true),sensitive:z.literal(true),privacyVersion:z.string(),sensitiveVersion:z.string(),mockAcknowledged:z.boolean()}).strict().parse(req.body);
  if(body.privacyVersion!==c.privacyVersion||body.sensitiveVersion!==c.sensitiveVersion)fail(409,'隐私说明已更新，请重新阅读');if(c.mock&&!body.mockAcknowledged)fail(400,'测试环境只能填写模拟信息');
  const recovery=token();const userId=randomUUID();
  const result=await tx(pool,'auth',undefined,async db=>{await db.query('SELECT pg_advisory_xact_lock_shared(704183)');const q=(await db.query('SELECT * FROM rr.questionnaires ORDER BY id LIMIT 1')).rows[0];if(!q?.accepting||!q.current_version_id)fail(409,'问卷暂未开放');await db.query("INSERT INTO rr.users(id,recovery_hash,mock,expires_at) VALUES($1,$2,$3,now()+$4*interval '1 day')",[userId,digest(recovery,c.tokenKey),c.mock,c.retentionDays]);const s=await session(db,'user',userId);await db.query('SET LOCAL ROLE rr_user');await db.query("SELECT set_config('rr.user_id',$1,true)",[userId]);await db.query('INSERT INTO rr.responses(user_id,version_id) VALUES($1,$2)',[userId,q.current_version_id]);await db.query("INSERT INTO rr.consent_events(user_id,kind,privacy_version,sensitive_version) VALUES($1,'grant',$2,$3)",[userId,c.privacyVersion,c.sensitiveVersion]);return s;});cookie(res,'user',result.raw);res.status(201).json({csrf:result.csrf,recovery});
 }));
 app.post('/api/recover',wrap(async(req,res)=>{await rate(req,'recover',10);const body=z.object({recovery:z.string().min(40).max(60)}).strict().parse(req.body);const s=await tx(pool,'auth',undefined,async db=>{const u=(await db.query('SELECT id FROM rr.users WHERE recovery_hash=$1 AND expires_at>now() AND mock=$2',[digest(body.recovery,c.tokenKey),c.mock])).rows[0];if(!u)fail(401,'恢复凭证无效或数据已删除');await db.query('DELETE FROM rr.sessions WHERE user_id=$1',[u.id]);return session(db,'user',u.id);});cookie(res,'user',s.raw);res.json({csrf:s.csrf});}));
 app.get('/api/me',requireAuth('user'),wrap(async(req,res)=>{const userId=req.session!.user_id!;const data=await tx(pool,'user',userId,async db=>{const u=(await db.query('SELECT id,public_id,status,mock,expires_at FROM rr.users WHERE id=$1',[userId])).rows[0];const r= u.status==='withdrawn'?null:await loadResponse(db,userId);const row=(await db.query('SELECT ciphertext FROM rr.user_contacts WHERE user_id=$1',[userId])).rows[0];return {user:u,...r,contact:row?unseal(row.ciphertext,c.encryptionKey,`${userId}:contact`):null};});res.json({...data,csrf:unseal(req.session!.csrf_ciphertext,c.encryptionKey,req.session!.token_hash)});}));
 app.put('/api/answers',requireAuth('user'),wrap(async(req,res)=>{await rate(req,'save',120);const body=z.object({answers:answersSchema,revision:z.number().int().min(0)}).strict().parse(req.body);const userId=req.session!.user_id!;
  const revision=await tx(pool,'user',userId,async db=>{const r=(await db.query('SELECT * FROM rr.responses WHERE user_id=$1 FOR UPDATE',[userId])).rows[0];if(!r||r.status!=='draft')fail(409,'已提交的回答请在确认页面修改');if(r.revision!==body.revision)fail(409,'回答已在另一页面更新，请重新加载');const clean=cleanAnswers(await questions(db,r.version_id),body.answers);await writeAnswers(db,userId,r.id,clean);return (await db.query('UPDATE rr.responses SET revision=revision+1,updated_at=now() WHERE id=$1 RETURNING revision',[r.id])).rows[0].revision;});res.json({revision});
 }));
 app.post('/api/submit',requireAuth('user'),wrap(async(req,res)=>{
  await rate(req,'submit',10);const body=z.object({answers:answersSchema,revision:z.number().int().min(0),contact:contactSchema,contactConsent:z.boolean(),confirm:z.literal(true),privacyVersion:z.string(),sensitiveVersion:z.string(),mockAcknowledged:z.boolean()}).strict().parse(req.body);if(body.contact&&!body.contactConsent)fail(400,'联系方式需另行确认同意');if(body.privacyVersion!==c.privacyVersion||body.sensitiveVersion!==c.sensitiveVersion)fail(409,'隐私说明已更新，请重新阅读');if(c.mock&&!body.mockAcknowledged)fail(400,'测试环境只能填写模拟信息');
  const userId=req.session!.user_id!;
  const data=await tx(pool,'user',userId,async db=>{const r=(await db.query('SELECT * FROM rr.responses WHERE user_id=$1 FOR UPDATE',[userId])).rows[0];if(!r)fail(409,'参与已撤回');if(r.status==='submitted')return {publicId:(await db.query('SELECT public_id FROM rr.users WHERE id=$1',[userId])).rows[0].public_id,revision:r.revision,duplicate:true};if(r.revision!==body.revision)fail(409,'回答已更新，请重新加载');await db.query('SELECT pg_advisory_xact_lock_shared(704183)');const q=(await db.query('SELECT accepting FROM rr.questionnaires LIMIT 1')).rows[0];if(!q.accepting)fail(409,'问卷暂停提交');const clean=cleanAnswers(await questions(db,r.version_id),body.answers,true);await writeAnswers(db,userId,r.id,clean);if(body.contact)await db.query('INSERT INTO rr.user_contacts(user_id,ciphertext) VALUES($1,$2) ON CONFLICT(user_id) DO UPDATE SET ciphertext=EXCLUDED.ciphertext',[userId,seal(body.contact,c.encryptionKey,`${userId}:contact`)]);else await db.query('DELETE FROM rr.user_contacts WHERE user_id=$1',[userId]);const publicId='RR-'+token().slice(0,12).toUpperCase();await db.query("UPDATE rr.users SET status='submitted',public_id=COALESCE(public_id,$2),expires_at=now()+$3*interval '1 day' WHERE id=$1",[userId,publicId,c.retentionDays]);const updated=(await db.query("UPDATE rr.responses SET status='submitted',submitted_at=now(),updated_at=now(),revision=revision+1 WHERE id=$1 RETURNING revision",[r.id])).rows[0];await db.query("INSERT INTO rr.consent_events(user_id,kind,privacy_version,sensitive_version) VALUES($1,'grant',$2,$3)",[userId,c.privacyVersion,c.sensitiveVersion]);return {publicId:(await db.query('SELECT public_id FROM rr.users WHERE id=$1',[userId])).rows[0].public_id,revision:updated.revision,duplicate:false};});res.json(data);
 }));
 app.post('/api/reopen',requireAuth('user'),wrap(async(req,res)=>{const userId=req.session!.user_id!;await tx(pool,'admin',undefined,async db=>{await db.query('SELECT id FROM rr.users WHERE id=$1 FOR UPDATE',[userId]);await db.query('DELETE FROM rr.matching_results WHERE user_a=$1 OR user_b=$1',[userId]);await db.query('SET LOCAL ROLE rr_user');await db.query("SELECT set_config('rr.user_id',$1,true)",[userId]);const r=await db.query("UPDATE rr.responses SET status='draft',revision=revision+1 WHERE user_id=$1 RETURNING id",[userId]);if(!r.rowCount)fail(409,'参与已撤回');await db.query("UPDATE rr.users SET status='draft',matching_status='pending' WHERE id=$1",[userId]);});res.json({ok:true});}));
 app.post('/api/recovery/rotate',requireAuth('user'),wrap(async(req,res)=>{const recovery=token();await tx(pool,'auth',undefined,async db=>{await db.query('UPDATE rr.users SET recovery_hash=$2 WHERE id=$1',[req.session!.user_id,digest(recovery,c.tokenKey)]);await db.query('DELETE FROM rr.sessions WHERE user_id=$1 AND token_hash<>$2',[req.session!.user_id,req.session!.token_hash]);});res.json({recovery});}));
 app.post('/api/withdraw',requireAuth('user'),wrap(async(req,res)=>{z.object({confirm:z.literal(true)}).strict().parse(req.body);const userId=req.session!.user_id!;await tx(pool,'admin',undefined,async db=>{await db.query('SELECT id FROM rr.users WHERE id=$1 FOR UPDATE',[userId]);await db.query('DELETE FROM rr.matching_results WHERE user_a=$1 OR user_b=$1',[userId]);await db.query('DELETE FROM rr.responses WHERE user_id=$1',[userId]);await db.query('DELETE FROM rr.user_contacts WHERE user_id=$1',[userId]);await db.query('SET LOCAL ROLE rr_user');await db.query("SELECT set_config('rr.user_id',$1,true)",[userId]);await db.query("UPDATE rr.users SET status='withdrawn' WHERE id=$1",[userId]);await db.query("INSERT INTO rr.consent_events(user_id,kind,privacy_version,sensitive_version) VALUES($1,'withdraw',$2,$3)",[userId,c.privacyVersion,c.sensitiveVersion]);});await tx(pool,'auth',undefined,async db=>{await db.query('DELETE FROM rr.sessions WHERE user_id=$1 AND token_hash<>$2',[userId,req.session!.token_hash]);await audit(db,req,'user.withdraw',userId);});res.json({ok:true});}));
 app.delete('/api/me',requireAuth('user'),wrap(async(req,res)=>{z.object({confirm:z.literal(true)}).strict().parse(req.body);await tx(pool,'auth',undefined,db=>audit(db,req,'user.delete',req.session!.user_id!));await tx(pool,'user',req.session!.user_id!,async db=>{await db.query('DELETE FROM rr.users WHERE id=$1',[req.session!.user_id]);});clear(res,'user');res.json({ok:true,backupNotice:'在线数据已删除。备份按保留周期失效；恢复时必须重放删除台账。'});}));
 app.post('/api/logout',requireAuth('user'),wrap(async(req,res)=>{await tx(pool,'auth',undefined,async db=>{await db.query('DELETE FROM rr.sessions WHERE token_hash=$1',[req.session!.token_hash]);});clear(res,'user');res.json({ok:true});}));
 app.post('/api/admin/login',wrap(async(req,res)=>{
  const body=z.object({username:z.string().min(1).max(80),password:z.string().min(1).max(200),otp:z.string().regex(/^\d{6}$/)}).strict().parse(req.body);await rate(req,'admin-login',5);await rate(req,'admin-account',10,900,body.username);
  const result=await tx(pool,'auth',undefined,async db=>{const a=(await db.query('SELECT * FROM rr.admin_users WHERE username=$1 AND active FOR UPDATE',[body.username])).rows[0];const passwordValid=await verifyPassword(body.password,a?.password_hash||'00000000000000000000000000000000:'+ '00'.repeat(64));if(!a||!passwordValid)return null;const n=verifyTotp(unseal<string>(a.totp_ciphertext,c.encryptionKey,`admin:${a.username}`),body.otp,Number(a.last_totp_counter));if(n===null)return null;await db.query('UPDATE rr.admin_users SET last_totp_counter=$2 WHERE id=$1',[a.id,n]);const s=await session(db,'admin',a.id);req.session={admin_id:a.id} as Session;await audit(db,req,'admin.login');return s;});if(!result){await tx(pool,'auth',undefined,db=>audit(db,req,'admin.login_failed'));fail(401,'账号、密码或动态验证码错误');}cookie(res,'admin',result!.raw);res.json({csrf:result!.csrf});
 }));
 app.get('/api/admin/session',requireAuth('admin'),wrap(async(req,res)=>res.json({csrf:unseal(req.session!.csrf_ciphertext,c.encryptionKey,req.session!.token_hash)})));
 app.post('/api/admin/reauth',requireAuth('admin'),wrap(async(req,res)=>{await rate(req,'reauth',5);const body=z.object({otp:z.string().regex(/^\d{6}$/)}).strict().parse(req.body);const valid=await tx(pool,'auth',undefined,async db=>{const a=(await db.query('SELECT * FROM rr.admin_users WHERE id=$1 AND active FOR UPDATE',[req.session!.admin_id])).rows[0];const n=verifyTotp(unseal<string>(a.totp_ciphertext,c.encryptionKey,`admin:${a.username}`),body.otp,Number(a.last_totp_counter));if(n===null)return false;await db.query('UPDATE rr.admin_users SET last_totp_counter=$2 WHERE id=$1',[a.id,n]);await db.query('UPDATE rr.sessions SET mfa_at=now() WHERE token_hash=$1',[req.session!.token_hash]);await audit(db,req,'admin.reauth');return true;});if(!valid)fail(401,'验证码无效或已使用');res.json({ok:true});}));
 app.post('/api/admin/logout',requireAuth('admin'),wrap(async(req,res)=>{await tx(pool,'auth',undefined,async db=>{await audit(db,req,'admin.logout');await db.query('DELETE FROM rr.sessions WHERE token_hash=$1',[req.session!.token_hash]);});clear(res,'admin');res.json({ok:true});}));
 app.use('/api/admin',requireAuth('admin'));
 app.get('/api/admin/users',wrap(async(req,res)=>{const query=z.object({search:z.string().max(60).optional(),status:z.enum(['draft','submitted','withdrawn']).optional(),matching:z.enum(['pending','reviewed','paused']).optional()}).parse(req.query);const data=await tx(pool,'admin',undefined,async db=>{await audit(db,req,'users.list');const users=(await db.query('SELECT id,public_id,status,matching_status,mock,created_at,expires_at FROM rr.users WHERE ($1::text IS NULL OR public_id ILIKE $1) AND ($2::text IS NULL OR status=$2) AND ($3::text IS NULL OR matching_status=$3) ORDER BY created_at DESC LIMIT 200',[query.search?`%${query.search}%`:null,query.status||null,query.matching||null])).rows;const stats=(await db.query('SELECT status,count(*)::integer count FROM rr.users GROUP BY status')).rows;return {users,stats};});res.json(data);}));
 app.get('/api/admin/users/:id',requireAuth('admin',true),wrap(async(req,res)=>{const id=uuid.parse(req.params.id);const data=await tx(pool,'admin',undefined,async db=>{const user=(await db.query('SELECT id,public_id,status,matching_status,mock,created_at,expires_at FROM rr.users WHERE id=$1',[id])).rows[0];if(!user)fail(404,'用户不存在');await audit(db,req,'sensitive.answers.read',id);return {user,...(user.status==='withdrawn'?{}:await loadResponse(db,id))};});res.json(data);}));
 app.get('/api/admin/users/:id/contact',requireAuth('admin',true),wrap(async(req,res)=>{const id=uuid.parse(req.params.id);const data=await tx(pool,'admin',undefined,async db=>{await audit(db,req,'sensitive.contact.read',id);const r=(await db.query('SELECT ciphertext FROM rr.user_contacts WHERE user_id=$1',[id])).rows[0];return r?unseal(r.ciphertext,c.encryptionKey,`${id}:contact`):null;});res.json({contact:data});}));
 app.patch('/api/admin/users/:id',wrap(async(req,res)=>{const id=uuid.parse(req.params.id);const body=z.object({matchingStatus:z.enum(['pending','reviewed','paused'])}).strict().parse(req.body);await tx(pool,'admin',undefined,async db=>{const r=await db.query('UPDATE rr.users SET matching_status=$2 WHERE id=$1',[id,body.matchingStatus]);if(!r.rowCount)fail(404,'用户不存在');await audit(db,req,'user.status.update',id);});res.json({ok:true});}));
 app.delete('/api/admin/users/:id',requireAuth('admin',true),wrap(async(req,res)=>{const id=uuid.parse(req.params.id);z.object({confirm:z.literal(true)}).strict().parse(req.body);await tx(pool,'admin',undefined,async db=>{await audit(db,req,'admin.user.delete',id);await db.query('DELETE FROM rr.users WHERE id=$1',[id]);});res.json({ok:true});}));
 app.get('/api/admin/questionnaires',wrap(async(req,res)=>{const data=await tx(pool,'admin',undefined,async db=>({questionnaire:(await db.query('SELECT * FROM rr.questionnaires LIMIT 1')).rows[0],versions:(await db.query('SELECT * FROM rr.questionnaire_versions ORDER BY version DESC')).rows,weights:(await db.query("SELECT value FROM rr.app_settings WHERE key='weights'")).rows[0]?.value||defaultWeights}));res.json(data);}));
 app.get('/api/admin/versions/:id',wrap(async(req,res)=>{const id=uuid.parse(req.params.id);res.json(await tx(pool,'admin',undefined,async db=>({questions:await questions(db,id)})));}));
 app.post('/api/admin/versions',wrap(async(req,res)=>{const body=z.object({from:uuid.optional()}).strict().parse(req.body);const version=await tx(pool,'admin',undefined,async db=>{await db.query('SELECT pg_advisory_xact_lock(704183)');const q=(await db.query('SELECT * FROM rr.questionnaires LIMIT 1 FOR UPDATE')).rows[0];const v=(await db.query("INSERT INTO rr.questionnaire_versions(questionnaire_id,version,status) SELECT $1,COALESCE(MAX(version),0)+1,'draft' FROM rr.questionnaire_versions WHERE questionnaire_id=$1 RETURNING *",[q.id])).rows[0];if(body.from)await db.query('INSERT INTO rr.questions(version_id,key,position,definition) SELECT $1,key,position,definition FROM rr.questions WHERE version_id=$2',[v.id,body.from]);await audit(db,req,'version.create',v.id);return v;});res.status(201).json(version);}));
 app.put('/api/admin/versions/:id',wrap(async(req,res)=>{const id=uuid.parse(req.params.id);const body=z.object({questions:z.array(questionSchema).min(1).max(80)}).strict().parse(req.body);await tx(pool,'admin',undefined,async db=>{const v=(await db.query('SELECT * FROM rr.questionnaire_versions WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!v||v.status!=='draft')fail(409,'只能编辑草稿版本');await db.query('DELETE FROM rr.questions WHERE version_id=$1',[id]);for(const [i,q] of body.questions.entries())await db.query('INSERT INTO rr.questions(version_id,key,position,definition) VALUES($1,$2,$3,$4)',[id,q.key,i,q]);await audit(db,req,'version.edit',id);});res.json({ok:true});}));
 app.post('/api/admin/versions/:id/publish',wrap(async(req,res)=>{const id=uuid.parse(req.params.id);await tx(pool,'admin',undefined,async db=>{await db.query('SELECT pg_advisory_xact_lock(704183)');const q=(await db.query('SELECT * FROM rr.questionnaires LIMIT 1 FOR UPDATE')).rows[0];const v=(await db.query('SELECT * FROM rr.questionnaire_versions WHERE id=$1 AND questionnaire_id=$2 FOR UPDATE',[id,q.id])).rows[0];if(!v||v.status!=='draft')fail(409,'版本不存在或已发布');validateQuestionnaire(await questions(db,id));await db.query("UPDATE rr.questionnaire_versions SET status='published',published_at=now() WHERE id=$1",[id]);await db.query('UPDATE rr.questionnaires SET current_version_id=$1,accepting=true WHERE id=$2',[id,q.id]);await audit(db,req,'version.publish',id);});res.json({ok:true});}));
 app.post('/api/admin/questionnaire/state',wrap(async(req,res)=>{const body=z.object({accepting:z.boolean()}).strict().parse(req.body);await tx(pool,'admin',undefined,async db=>{await db.query('SELECT pg_advisory_xact_lock(704183)');await db.query('UPDATE rr.questionnaires SET accepting=$1 WHERE current_version_id IS NOT NULL',[body.accepting]);await audit(db,req,body.accepting?'questionnaire.resume':'questionnaire.pause');});res.json({ok:true});}));
 app.put('/api/admin/weights',wrap(async()=>fail(503,'匹配算法暂未启用，权重接口仅作为后续框架预留')));
 async function pair(db:SQL,a:string,b:string){const users=(await db.query("SELECT id,status,matching_status,mock FROM rr.users WHERE id=ANY($1::uuid[]) ORDER BY id FOR SHARE",[[a,b]])).rows;if(users.length!==2)fail(404,'请选择两位不同用户');const profiles:Profile[]=[];for(const id of [a,b]){const u=users.find(x=>x.id===id)!;let answers:Answers={};if(u.status!=='withdrawn')answers=(await loadResponse(db,id)).answers;profiles.push({id,answers,active:u.mock===c.mock&&u.status==='submitted'&&u.matching_status!=='paused'});}const rejected=(await db.query("SELECT 1 FROM rr.matching_feedback f JOIN rr.matching_results r ON r.id=f.result_id WHERE r.user_a=$1 AND r.user_b=$2 AND f.decision='no' LIMIT 1",[a,b])).rowCount!==0;return manualReport(profiles[0],profiles[1],rejected);}
 app.get('/api/admin/suggestions',requireAuth('admin',true),wrap(async(_req,res)=>res.json({suggestions:[],mode:'manual',message:'自动推荐和算法打分暂未启用，请由管理员选择候选并亲自授权'})));
 app.post('/api/admin/matches',requireAuth('admin',true),wrap(async(req,res)=>{const body=z.object({a:uuid,b:uuid,save:z.boolean()}).strict().parse(req.body);const [a,b]=[body.a,body.b].sort();if(a===b)fail(400,'请选择两位不同用户');const data=await tx(pool,'admin',undefined,async db=>{const report=await pair(db,a,b);await audit(db,req,body.save?'sensitive.matching.candidate.create':'sensitive.matching.preview',`${a}:${b}`);let id=null;if(body.save){id=(await db.query('INSERT INTO rr.matching_results(user_a,user_b,report_ciphertext,score,eligible) VALUES($1,$2,$3,$4,$5) RETURNING id',[a,b,seal(report,c.encryptionKey,`match:${a}:${b}`),report.score,report.eligible])).rows[0].id;for(const user of [a,b])await db.query("INSERT INTO rr.matching_feedback(result_id,user_id,decision) VALUES($1,$2,'pending')",[id,user]);}return {id,a,b,report};});res.json(data);}));
 app.get('/api/admin/matches',requireAuth('admin',true),wrap(async(req,res)=>{const matches=await tx(pool,'admin',undefined,async db=>{await audit(db,req,'sensitive.matching.read');const rows=(await db.query('SELECT r.*,a.public_id label_a,b.public_id label_b FROM rr.matching_results r JOIN rr.users a ON a.id=r.user_a JOIN rr.users b ON b.id=r.user_b ORDER BY r.created_at DESC LIMIT 100')).rows;const out=[];for(const row of rows){const feedback=(await db.query('SELECT user_id,decision,recorded_at FROM rr.matching_feedback WHERE result_id=$1',[row.id])).rows;const reviewed=(await db.query("SELECT count(*)::int count FROM rr.users WHERE id=ANY($1::uuid[]) AND status='submitted' AND matching_status='reviewed'",[[row.user_a,row.user_b]])).rows[0].count===2;const current=await pair(db,row.user_a,row.user_b);out.push({...row,report_ciphertext:undefined,score:null,report:current,feedback,canIntroduce:row.authorization_status==='authorized'&&!!row.authorized_by&&!!row.authorized_at&&reviewed&&current.eligible&&feedback.length===2&&feedback.every(x=>x.decision==='yes')});}return out;});res.json({matches});}));
 app.post('/api/admin/matches/:id/authorization',requireAuth('admin',true),wrap(async(req,res)=>{
  const id=uuid.parse(req.params.id);const body=z.object({decision:z.enum(['authorize','reject']),confirmedManually:z.literal(true),basicConditionsReviewed:z.literal(true)}).strict().parse(req.body);
  await tx(pool,'admin',undefined,async db=>{
   const match=(await db.query('SELECT * FROM rr.matching_results WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!match)fail(404,'候选记录不存在');
   if(body.decision==='authorize'){
    const report=await pair(db,match.user_a,match.user_b);if(!report.eligible)fail(409,'双方基本条件不满足，不能授权介绍');
    const reviewed=(await db.query("SELECT count(*)::int count FROM rr.users WHERE id=ANY($1::uuid[]) AND status='submitted' AND matching_status='reviewed'",[[match.user_a,match.user_b]])).rows[0].count===2;
    const feedback=(await db.query('SELECT decision FROM rr.matching_feedback WHERE result_id=$1 FOR UPDATE',[id])).rows;
    if(!reviewed||feedback.length!==2||!feedback.every(x=>x.decision==='yes'))fail(409,'请先完成人工审核并分别记录双方明确同意');
    await db.query("UPDATE rr.matching_results SET authorization_status='authorized',authorized_by=$2,authorized_at=now() WHERE id=$1",[id,req.session!.admin_id]);
   }else await db.query("UPDATE rr.matching_results SET authorization_status='rejected',authorized_by=NULL,authorized_at=NULL WHERE id=$1",[id]);
   await audit(db,req,body.decision==='authorize'?'matching.authorize':'matching.reject',id);
  });res.json({ok:true});
 }));
 app.put('/api/admin/matches/:id/feedback',requireAuth('admin',true),wrap(async(req,res)=>{const id=uuid.parse(req.params.id);const body=z.object({userId:uuid,decision:z.enum(['pending','yes','no']),confirmedExternally:z.literal(true)}).strict().parse(req.body);await tx(pool,'admin',undefined,async db=>{const r=(await db.query('SELECT user_a,user_b FROM rr.matching_results WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!r||![r.user_a,r.user_b].includes(body.userId))fail(400,'用户不属于该组合');await db.query('UPDATE rr.matching_feedback SET decision=$3,recorded_at=now() WHERE result_id=$1 AND user_id=$2',[id,body.userId,body.decision]);await db.query("UPDATE rr.matching_results SET authorization_status=CASE WHEN $2='no' THEN 'rejected' ELSE 'pending' END,authorized_by=NULL,authorized_at=NULL WHERE id=$1",[id,body.decision]);await audit(db,req,'matching.feedback.update',id);});res.json({ok:true});}));
 app.post('/api/admin/export',requireAuth('admin',true),wrap(async(req,res)=>{const body=z.object({includeContacts:z.boolean(),purpose:z.enum(['user_request','manual_review','backup_review'])}).strict().parse(req.body);const data=await tx(pool,'admin',undefined,async db=>{await audit(db,req,'sensitive.export');const users=(await db.query('SELECT id,public_id,status,matching_status,mock,created_at,expires_at FROM rr.users ORDER BY id')).rows;const records=[];for(const u of users){const r=u.status==='withdrawn'?null:await loadResponse(db,u.id);const contact=body.includeContacts?(await db.query('SELECT ciphertext FROM rr.user_contacts WHERE user_id=$1',[u.id])).rows[0]:null;records.push({user:u,response:r?.response,answers:r?.answers,questions:r?.questions,contact:contact?unseal(contact.ciphertext,c.encryptionKey,`${u.id}:contact`):undefined});}return records;});res.setHeader('Content-Disposition','attachment; filename="renzhen-export.json"');res.json({generatedAt:new Date().toISOString(),records:data});}));
 app.get('/api/admin/audit',wrap(async(req,res)=>{const logs=await tx(pool,'admin',undefined,async db=>{await audit(db,req,'audit.read');return (await db.query('SELECT id,admin_id,action,target_hash,request_id,created_at FROM rr.audit_logs ORDER BY created_at DESC LIMIT 200')).rows;});res.json({logs});}));
 app.post('/api/admin/ai/analyze',wrap(async(_req,_res)=>fail(503,'AI 分析默认关闭；尚未配置经过审核的数据处理服务')));
 app.use('/api',(_req,res)=>res.status(404).json({error:'接口不存在'}));
 app.use(express.static(path.resolve('dist'),{setHeaders:(res,file)=>res.setHeader('Cache-Control',file.endsWith('index.html')?'no-store':'public, max-age=31536000, immutable')}));
 app.get(/.*/,(_req,res)=>{res.setHeader('Cache-Control','no-store');res.sendFile(path.resolve('dist/index.html'));});
 app.use((err:unknown,req:Authed,res:Response,_next:NextFunction)=>{const status=err instanceof HttpError?err.status:err instanceof z.ZodError?400:err instanceof Error&&(/答案|请完成|年龄|问卷|匹配必需|分支|量表|选项|问题标识/.test(err.message))?400:500;const message=status===500?'服务暂时不可用，请稍后重试':err instanceof z.ZodError?'输入格式不正确':err instanceof Error?err.message:'请求失败';if(status===500)console.error(JSON.stringify({event:'request.error',requestId:req.requestId,code:(err as {code?:string})?.code||'internal'}));res.status(status).json({error:message,requestId:req.requestId});});
 return app;
}
