import { randomBytes,createCipheriv,createDecipheriv,createHmac,scrypt as scryptCb,timingSafeEqual } from 'node:crypto';
const scrypt=(password:string,salt:string,length:number,options:{N:number;r:number;p:number;maxmem:number})=>new Promise<Buffer>((resolve,reject)=>scryptCb(password,salt,length,options,(error,key)=>error?reject(error):resolve(key)));
export const token=()=>randomBytes(32).toString('base64url');
export const digest=(value:string,key:string)=>createHmac('sha256',Buffer.from(key,'hex')).update(value).digest('hex');
export function seal(value:unknown,key:string,aad:string){const iv=randomBytes(12);const c=createCipheriv('aes-256-gcm',Buffer.from(key,'hex'),iv);c.setAAD(Buffer.from(aad));return ['v1',iv.toString('base64'),Buffer.concat([c.update(JSON.stringify(value),'utf8'),c.final()]).toString('base64'),c.getAuthTag().toString('base64')].join('.');}
export function unseal<T=unknown>(value:string,key:string,aad:string):T{const [version,iv,data,tag]=value.split('.');if(version!=='v1')throw new Error('Unknown encryption format');const c=createDecipheriv('aes-256-gcm',Buffer.from(key,'hex'),Buffer.from(iv,'base64'));c.setAAD(Buffer.from(aad));c.setAuthTag(Buffer.from(tag,'base64'));return JSON.parse(Buffer.concat([c.update(Buffer.from(data,'base64')),c.final()]).toString('utf8'));}
export async function hashPassword(password:string){const salt=randomBytes(16).toString('hex');const result=await scrypt(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024}) as Buffer;return `${salt}:${result.toString('hex')}`;}
export async function verifyPassword(password:string,stored:string){const [salt,hash]=stored.split(':');const result=await scrypt(password,salt,64,{N:32768,r:8,p:1,maxmem:64*1024*1024}) as Buffer;const expected=Buffer.from(hash,'hex');return result.length===expected.length&&timingSafeEqual(result,expected);}
const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export function newTotpSecret(){const bytes=randomBytes(20);let bits='';for(const b of bytes)bits+=b.toString(2).padStart(8,'0');let out='';for(let i=0;i<bits.length;i+=5)out+=alphabet[parseInt(bits.slice(i,i+5),2)];return out;}
function decode32(s:string){let bits='';for(const c of s.toUpperCase().replace(/=+$/,'')){const n=alphabet.indexOf(c);if(n<0)throw new Error('Invalid base32');bits+=n.toString(2).padStart(5,'0');}return Buffer.from(bits.match(/.{8}/g)!.map(x=>parseInt(x,2)));}
export function totp(secret:string,counter:number){const buf=Buffer.alloc(8);buf.writeBigUInt64BE(BigInt(counter));const h=createHmac('sha1',decode32(secret)).update(buf).digest();const offset=h[19]&15;return ((h.readUInt32BE(offset)&0x7fffffff)%1000000).toString().padStart(6,'0');}
export function verifyTotp(secret:string,code:string,last=-1,now=Date.now()){if(!/^\d{6}$/.test(code))return null;const n=Math.floor(now/30000);for(const c of [n,n-1,n+1])if(c>last&&timingSafeEqual(Buffer.from(totp(secret,c)),Buffer.from(code)))return c;return null;}
