import EmbeddedPostgres from 'embedded-postgres';import pg from 'pg';import {randomBytes,randomUUID} from 'node:crypto';import {mkdir,readFile,writeFile,access} from 'node:fs/promises';import path from 'node:path';import {migrate} from './migrate.js';import {hashPassword,newTotpSecret,seal,digest,token} from '../server/security.js';import type {Config} from '../server/config.js';
export async function localDatabase(dir:string,port:number,persistent=true){
 await mkdir(dir,{recursive:true,mode:0o700});let state:{rootPassword:string;runtimePassword:string;encryptionKey:string;tokenKey:string;adminPassword:string;totp:string};
 try{state=JSON.parse(await readFile(path.join(dir,'state.json'),'utf8'));}catch{state={rootPassword:token(),runtimePassword:token(),encryptionKey:randomBytes(32).toString('hex'),tokenKey:randomBytes(32).toString('hex'),adminPassword:token(),totp:newTotpSecret()};await writeFile(path.join(dir,'state.json'),JSON.stringify(state),{mode:0o600});}
 const postgres=new EmbeddedPostgres({databaseDir:path.join(dir,'pg'),user:'postgres',password:state.rootPassword,port,persistent,onLog:()=>{},onError:()=>{},postgresFlags:['-h','127.0.0.1'],initdbFlags:['--encoding=UTF8','--locale=C']});
 try{await access(path.join(dir,'pg/PG_VERSION'));}catch{await postgres.initialise();}
 await postgres.start();const migrationUrl=`postgresql://postgres:${state.rootPassword}@127.0.0.1:${port}/postgres`;
 try{await migrate(migrationUrl);const pool=new pg.Pool({connectionString:migrationUrl});try{const sql=(await pool.query("SELECT format('ALTER ROLE rr_runtime PASSWORD %L',$1::text)",[state.runtimePassword])).rows[0].format;await pool.query(sql);const r=await pool.query("SELECT 1 FROM rr.admin_users WHERE username='local-admin'");if(!r.rowCount)await pool.query('INSERT INTO rr.admin_users(username,password_hash,totp_ciphertext) VALUES($1,$2,$3)',['local-admin',await hashPassword(state.adminPassword),seal(state.totp,state.encryptionKey,'admin:local-admin')]);await pool.query("UPDATE rr.questionnaire_versions SET status='published',published_at=now() WHERE version=1 AND status='draft'");await pool.query('UPDATE rr.questionnaires SET current_version_id=(SELECT id FROM rr.questionnaire_versions WHERE version=1),accepting=true WHERE current_version_id IS NULL');}finally{await pool.end();}}
 catch(e){await postgres.stop();throw e;}
 const config:Config={databaseUrl:`postgresql://rr_runtime:${state.runtimePassword}@127.0.0.1:${port}/postgres`,encryptionKey:state.encryptionKey,tokenKey:state.tokenKey,origin:'http://127.0.0.1:5173',production:false,mock:true,approved:false,port:8080,retentionDays:90,privacyVersion:'draft-2026-10-08',sensitiveVersion:'draft-2026-10-08',processorName:'待人工核验的项目运营主体',privacyContact:'待人工核验的隐私联系渠道',trustProxy:0};
 return {postgres,config,state,migrationUrl};
}
export async function seedMock(url:string,c:Config){const pool=new pg.Pool({connectionString:url});try{if((await pool.query('SELECT 1 FROM rr.users LIMIT 1')).rowCount)return;const version=(await pool.query('SELECT current_version_id FROM rr.questionnaires LIMIT 1')).rows[0].current_version_id;for(let i=0;i<6;i++){const id=randomUUID();const r=randomUUID();const recovery=token();await pool.query("INSERT INTO rr.users(id,public_id,recovery_hash,status,matching_status,mock,expires_at) VALUES($1,$2,$3,'submitted','reviewed',true,now()+interval '90 days')",[id,`RR-MOCK-00${i+1}`,digest(recovery,c.tokenKey)]);await pool.query("INSERT INTO rr.responses(id,user_id,version_id,status,submitted_at) VALUES($1,$2,$3,'submitted',now())",[r,id,version]);const answers={age:26+i,gender:i%2?'男性':'女性',seeking:[i%2?'女性':'男性'],age_min:24,age_max:36,relationship:'长期且排他的恋爱关系',match_accept:'愿意',values_honesty:5,values_independence:3+i%2,values_growth:4,future_city:'上海',future_children:i<4?'尚未确定':'不希望',intimacy_space:3,intimacy_expression:4,communication:i%3?'先冷静再讨论':'当下讨论',communication_checkin:5,interests:i%2?['运动与户外','阅读与电影']:['阅读与电影','音乐与展览'],sleep:'偏早睡早起',social:'安排一些活动',pets:'否',about:'这是自动生成的虚构回答，仅用于功能测试。'};for(const [key,value]of Object.entries(answers))await pool.query('INSERT INTO rr.response_answers(response_id,user_id,question_key,ciphertext) VALUES($1,$2,$3,$4)',[r,id,key,seal(value,c.encryptionKey,`${id}:${r}:${key}`)]);}}finally{await pool.end();}}
