import type {Pool,PoolClient} from 'pg';import {digest} from '../server/security.js';
// Names and ordering are static. Deferred FK checks let questions precede published versions.
export const tables=['questionnaires','questions','questionnaire_versions','users','user_contacts','responses','response_answers','invitation_codes','matching_results','matching_feedback','admin_users','consent_events','audit_logs','app_settings','rate_limits','sessions'] as const;
export type Snapshot={schemaVersion:1;createdAt:string;tables:Record<string,Record<string,unknown>[]>};
export type Ledger={capturedAt:string;rows:{action:string;target_hash:string;created_at:string}[]};
export async function capture(pool:Pool):Promise<Snapshot>{const db=await pool.connect();try{await db.query('BEGIN ISOLATION LEVEL REPEATABLE READ READ ONLY');const data:Snapshot={schemaVersion:1,createdAt:new Date().toISOString(),tables:{}};for(const table of tables){const rows=(await db.query(`SELECT * FROM rr.${table} LIMIT 10001`)).rows;if(rows.length>10000)throw new Error('Snapshot exceeds beta limits; use approved native cloud backup');data.tables[table]=rows;}await db.query('COMMIT');return data;}catch(e){await db.query('ROLLBACK');throw e;}finally{db.release();}}
export async function captureLedger(pool:Pool):Promise<Ledger>{const rows=(await pool.query("SELECT action,target_hash,created_at FROM rr.audit_logs WHERE action IN ('user.delete','admin.user.delete','retention.delete','user.withdraw') ORDER BY created_at")).rows;return {capturedAt:new Date().toISOString(),rows};}
export async function restoreSnapshot(pool:Pool,snapshot:Snapshot,ledger:Ledger,tokenKey:string){if(snapshot.schemaVersion!==1||tables.some(t=>!Array.isArray(snapshot.tables[t])))throw new Error('Unsupported snapshot schema');if(new Date(ledger.capturedAt)<new Date(snapshot.createdAt))throw new Error('Ledger must be newer than snapshot');const db=await pool.connect();try{await db.query('BEGIN');await db.query('SELECT pg_advisory_xact_lock(704182)');const existing=(await db.query('SELECT (SELECT count(*) FROM rr.users)+(SELECT count(*) FROM rr.admin_users)+(SELECT count(*) FROM rr.sessions) AS count')).rows[0];if(Number(existing.count)!==0)throw new Error('Restore target must be an empty, newly migrated isolated database');await db.query('SET CONSTRAINTS ALL DEFERRED');await db.query(`TRUNCATE ${tables.map(t=>'rr.'+t).join(',')} CASCADE`);
 for(const table of tables){const columns=(await db.query("SELECT column_name,data_type FROM information_schema.columns WHERE table_schema='rr' AND table_name=$1 ORDER BY ordinal_position",[table])).rows;for(const row of snapshot.tables[table]){const allowed=columns.map(x=>x.column_name);if(Object.keys(row).some(k=>!allowed.includes(k)))throw new Error('Unexpected snapshot column');const present=columns.filter(col=>Object.hasOwn(row,col.column_name));const keys=present.map(col=>col.column_name);await db.query(`INSERT INTO rr.${table}(${keys.map(k=>'"'+k+'"').join(',')}) VALUES(${keys.map((_,i)=>'$'+(i+1)).join(',')})`,present.map(col=>col.data_type==='jsonb'?JSON.stringify(row[col.column_name]):row[col.column_name]));}}
 const deleted=new Set(ledger.rows.filter(x=>x.action!=='user.withdraw').map(x=>x.target_hash));const withdrawn=new Set(ledger.rows.filter(x=>x.action==='user.withdraw').map(x=>x.target_hash));
 for(const user of (await db.query('SELECT id,expires_at FROM rr.users')).rows){const hash=digest(user.id,tokenKey);if(deleted.has(hash)||new Date(user.expires_at)<new Date()){await db.query('DELETE FROM rr.users WHERE id=$1',[user.id]);}else if(withdrawn.has(hash)){await db.query('DELETE FROM rr.responses WHERE user_id=$1',[user.id]);await db.query('DELETE FROM rr.user_contacts WHERE user_id=$1',[user.id]);await db.query('DELETE FROM rr.matching_results WHERE user_a=$1 OR user_b=$1',[user.id]);await db.query("UPDATE rr.users SET status='withdrawn' WHERE id=$1",[user.id]);}}
 for(const row of ledger.rows)await db.query('INSERT INTO rr.audit_logs(action,target_hash,created_at) VALUES($1,$2,$3)',[row.action,row.target_hash,row.created_at]);await db.query('DELETE FROM rr.sessions');await db.query('DELETE FROM rr.rate_limits');await db.query('UPDATE rr.questionnaires SET accepting=false');await db.query("UPDATE rr.matching_results SET score=NULL,authorization_status='pending',authorized_by=NULL,authorized_at=NULL");await db.query('COMMIT');
 }catch(e){await db.query('ROLLBACK');throw e;}finally{db.release();}}
