import {useEffect,useRef,useState} from 'react';import {api} from './api';import {PrivacyText,type Meta} from './privacy';import {visibleQuestions,cleanAnswers,type Question,type Answers} from '../shared/model';
type Me={user:{id:string;public_id:string|null;status:string;expires_at:string};response?:{id:string;version_id:string;revision:number;status:string};answers?:Answers;questions?:Question[];contact?:{channel:string;value:string}|null};
export function UserApp(){
 const [meta,setMeta]=useState<Meta|null>(null),[me,setMe]=useState<Me|null>(null),[stage,setStage]=useState('welcome'),[returnStage,setReturnStage]=useState('welcome'),[index,setIndex]=useState(0),[answers,setAnswers]=useState<Answers>({}),[recovery,setRecovery]=useState(''),[recoveryInput,setRecoveryInput]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saveState,setSaveState]=useState('已自动保存');
 const [adult,setAdult]=useState(false),[privacy,setPrivacy]=useState(false),[sensitive,setSensitive]=useState(false),[mockAck,setMockAck]=useState(false),[contact,setContact]=useState(''),[channel,setChannel]=useState('微信'),[contactConsent,setContactConsent]=useState(false),[confirm,setConfirm]=useState(false);
 const revision=useRef(0),latest=useRef<Answers>({}),saved=useRef(''),chain=useRef(Promise.resolve()),draftEnabled=useRef(false);
 function ingest(data:Me){setMe(data);revision.current=data.response?.revision||0;latest.current=data.answers||{};saved.current=JSON.stringify(latest.current);setAnswers(latest.current);setContact(data.contact?.value||'');setChannel(data.contact?.channel||'微信');setContactConsent(!!data.contact);draftEnabled.current=data.user.status==='draft';setStage(data.user.status==='draft'?'form':data.user.status==='withdrawn'?'withdrawn':'submitted');}
 useEffect(()=>{api<Meta>('/api/meta').then(setMeta).catch(e=>setError(e.message));api<Me>('/api/me').then(ingest).catch(()=>{});},[]);
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function refresh(){ingest(await api<Me>('/api/me'));}
 function saveNow(){const pending=async()=>{if(!draftEnabled.current)return;const snapshot=latest.current,serial=JSON.stringify(snapshot);if(serial===saved.current)return;setSaveState('正在保存…');try{const r=await api('/api/answers','PUT',{answers:snapshot,revision:revision.current});revision.current=r.revision;saved.current=serial;setSaveState('已自动保存');}catch(e){setSaveState('保存失败，请重试');throw e;}};const next=chain.current.catch(()=>{}).then(pending);chain.current=next;return next;}
 useEffect(()=>{latest.current=answers;if(stage!=='form'&&stage!=='review')return;const timeout=setTimeout(()=>{void saveNow().catch(e=>setError(e.message));},650);return ()=>clearTimeout(timeout);},[answers,stage]);
 const questions=me?.questions||[],visible=visibleQuestions(questions,answers),q=visible[Math.min(index,visible.length-1)];
 function change(value:Answers[string]|undefined){const next={...answers};if(value===undefined)delete next[q.key];else next[q.key]=value;latest.current=next;setAnswers(next);setError('');setSaveState('等待保存…');}
 const next=()=>run(async()=>{if(q.required)cleanAnswers([q],answers,true);await saveNow();if(index+1>=visible.length){setStage('review');setConfirm(false);}else setIndex(index+1);});
 const start=()=>run(async()=>{const r=await api('/api/enroll','POST',{adult,privacy,sensitive,privacyVersion:meta!.privacyVersion,sensitiveVersion:meta!.sensitiveVersion,mockAcknowledged:mockAck});setRecovery(r.recovery);setIndex(0);await refresh();});
 const submit=()=>run(async()=>{await saveNow();const r=await api('/api/submit','POST',{answers:latest.current,revision:revision.current,contact:contact.trim()?{channel,value:contact.trim()}:null,contactConsent,confirm,privacyVersion:meta!.privacyVersion,sensitiveVersion:meta!.sensitiveVersion,mockAcknowledged:mockAck||meta!.mock});revision.current=r.revision;draftEnabled.current=false;await refresh();});
 return <div className="user-shell"><header className="site-header"><a href="/" className="wordmark">认真认识<span className="brand-dot"/></a><span className="beta-pill">PRIVATE BETA</span></header>
 {meta?.mock&&<div className="test-banner">模拟测试中 · 请使用虚构信息</div>}
 <main>
 {stage==='welcome'&&<><section className="hero"><div className="hero-tag"><span/>上海 · 首轮内测</div><h1>认真认识。<br/><span>从真实的自己开始。</span></h1><p className="hero-copy">给长期关系，一个慢慢开始的机会。<br/>关于你的价值观、生活与期待，<br className="mobile-br"/>我们想认真听一听。</p><button className="button primary" disabled={!meta?.accepting||busy} onClick={()=>setStage('consent')}>{meta?.accepting?'开始认识自己':'问卷暂未开放'}<span>↗</span></button><p className="hero-meta">仅限成年人 · 约 6–10 分钟 · 首轮免费</p><div className="orbital-mark" aria-hidden="true"><div/><div/></div></section>
 <section className="principles"><div className="section-intro"><span className="eyebrow">A THOUGHTFUL START</span><h2>少一点匆忙，<br/>多一点了解。</h2></div><div className="principle-grid"><article><span className="number">01</span><h3>先了解，再介绍。</h3><p>从价值观与生活期待出发。管理员逐一审核，双方确认后再介绍。</p></article><article><span className="number">02</span><h3>你的回答，私密保管。</h3><p>没有公开个人档案。其他参与者无法查看你的问卷。</p></article><article><span className="number">03</span><h3>每一步，由你决定。</h3><p>双方确认后才会介绍。你可以随时修改、撤回或删除。</p></article></div></section><section className="restore-strip"><div><h3>已经开始填写？</h3><p>用安全恢复凭证继续。公开用户 ID 无法用于登录。</p></div><button className="text-button" onClick={()=>setStage('recover')}>恢复填写 <span>→</span></button></section></>}
 {stage==='consent'&&<section className="flow-card consent-card"><span className="eyebrow">BEFORE WE BEGIN</span><h1>开始之前，<br/>先把选择权交给你。</h1><p className="lead">请分别阅读并确认。你可以拒绝同意并退出，也可以在参与后随时撤回。</p><label className="check-row"><input type="checkbox" checked={adult} onChange={e=>setAdult(e.target.checked)}/><span>我已年满 18 周岁。<small>首轮服务仅面向成年参与者。</small></span></label><div className="consent-section"><PrivacyText meta={meta!}/></div><label className="check-row"><input type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)}/><span>我已阅读并同意个人信息处理规则。</span></label><div className="consent-section"><PrivacyText meta={meta!} sensitive/></div><label className="check-row"><input type="checkbox" checked={sensitive} onChange={e=>setSensitive(e.target.checked)}/><span>我单独同意上述敏感个人信息处理。<small>包括可能揭示性取向及亲密关系的信息，用于人工审核和匹配。</small></span></label>{meta?.mock&&<label className="check-row"><input type="checkbox" checked={mockAck} onChange={e=>setMockAck(e.target.checked)}/><span>我仅填写虚构的测试信息。</span></label>}<div className="flow-actions"><button className="text-button" onClick={()=>setStage('welcome')}>返回</button><button className="button primary" disabled={busy||!adult||!privacy||!sensitive||(meta!.mock&&!mockAck)} onClick={start}>同意并开始 <span>→</span></button></div></section>}
 {stage==='recover'&&<section className="flow-card narrow"><span className="eyebrow">PICK UP WHERE YOU LEFT OFF</span><h1>继续你的回答。</h1><p className="lead">粘贴之前保存的安全恢复凭证。它相当于你的钥匙，请不要分享给别人。</p><label className="field-label">安全恢复凭证<input autoComplete="off" spellCheck={false} type="password" value={recoveryInput} onChange={e=>setRecoveryInput(e.target.value)} placeholder="输入恢复凭证"/></label><div className="flow-actions"><button className="text-button" onClick={()=>setStage('welcome')}>返回</button><button className="button primary" disabled={busy||!recoveryInput} onClick={()=>run(async()=>{await api('/api/recover','POST',{recovery:recoveryInput.trim()});setRecoveryInput('');await refresh();})}>恢复填写 →</button></div></section>}
 {stage==='form'&&q&&<section className="flow-card question-card"><div className="progress-meta"><span>关于你 · {index+1} / {visible.length}</span><span className="save-state" role="status">{saveState}</span></div><div className="progress-track"><div style={{width:`${(index+1)/visible.length*100}%`}}/></div>{recovery&&<details className="recovery-note"><summary>请保存你的安全恢复凭证</summary><Recovery value={recovery}/></details>}<span className="eyebrow">{q.sensitive?'PRIVATE · 敏感信息':'GETTING TO KNOW YOU'}</span><h1>{q.title}</h1>{q.description&&<p className="lead">{q.description}</p>}<div className="answer-space"><QuestionInput question={q} value={answers[q.key]} onChange={change}/></div><div className="flow-actions"><button className="text-button" disabled={index===0||busy} onClick={()=>setIndex(Math.max(0,index-1))}>← 上一题</button><button className="button primary" disabled={busy} onClick={next}>{index+1===visible.length?'查看并提交':'下一题'} →</button></div><button className="text-button subtle" onClick={()=>run(async()=>{await saveNow();setStage('manage');})}>保存并查看参与设置</button></section>}
 {stage==='review'&&<section className="flow-card"><span className="eyebrow">ONE LAST LOOK</span><h1>这就是你，<br/>此刻的答案。</h1><p className="lead">提交前再看一遍。答案没有对错，提交后仍可安全修改。</p><div className="review-list">{visible.map((x,i)=><div key={x.key}><span>{x.title}</span><strong>{format(answers[x.key])}</strong><button className="text-button" onClick={()=>{setIndex(i);setStage('form');}}>修改</button></div>)}</div><div className="contact-panel"><h3>希望我们通过什么方式联系你？</h3><p>选填。联系方式只供管理员征求介绍意愿，单独加密保管。</p><div className="field-pair"><select value={channel} onChange={e=>setChannel(e.target.value)}><option>微信</option><option>手机</option><option>邮箱</option></select><input type="text" autoComplete="off" maxLength={120} value={contact} onChange={e=>setContact(e.target.value)} placeholder={meta?.mock?'例如：mock_contact（虚构）':'填写联系方式（选填）'}/></div>{contact&&<label className="check-row"><input type="checkbox" checked={contactConsent} onChange={e=>setContactConsent(e.target.checked)}/><span>我同意管理员为征求介绍意愿使用此联系方式。</span></label>}</div><label className="check-row"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/><span>我确认以上回答，并同意按已阅读的规则提交。{meta?.mock&&'本次仅提交虚构测试信息。'}</span></label><div className="flow-actions"><button className="text-button" onClick={()=>setStage('form')}>返回问卷</button><button className="button primary" disabled={busy||!confirm||(!!contact&&!contactConsent)} onClick={submit}>确认提交 ↗</button></div></section>}
 {stage==='submitted'&&<section className="flow-card narrow success-card"><div className="success-symbol">✓</div><span className="eyebrow">A GOOD BEGINNING</span><h1>谢谢你的认真。</h1><p className="lead">回答已保存。我们会仔细阅读，<br/>合适的介绍需要双方确认后才会发生。</p><div className="id-card"><span>你的随机用户 ID</span><strong>{me?.user.public_id}</strong><small>用于沟通时识别记录，无法用于访问回答。</small></div>{recovery?<Recovery value={recovery}/>:<p className="notice">请确认你已保管恢复凭证。可在参与设置中重新生成。</p>}<button className="button primary" onClick={()=>setStage('manage')}>管理我的参与 →</button></section>}
 {(stage==='manage'||stage==='withdrawn')&&<section className="flow-card narrow"><span className="eyebrow">ALWAYS YOUR CHOICE</span><h1>{me?.user.status==='withdrawn'?'已撤回参与。':'你始终拥有选择权。'}</h1><p className="lead">{me?.user.status==='withdrawn'?'已停止匹配，在线问卷回答、联系方式及匹配记录已移除。你还可以删除剩余个人记录。':`记录将于 ${new Date(me?.user.expires_at||'').toLocaleDateString('zh-CN')} 到期。修改回答会重置审核及介绍确认。`}</p>{recovery&&<Recovery value={recovery}/>}<div className="manage-actions">{me?.user.status!=='withdrawn'&&<><button className="management-row" disabled={busy} onClick={()=>run(async()=>{if(me?.user.status==='submitted')await api('/api/reopen','POST',{});setIndex(0);await refresh();})}>修改或继续填写 <span>→</span></button><button className="management-row" disabled={busy} onClick={()=>run(async()=>{const r=await api('/api/recovery/rotate','POST',{});setRecovery(r.recovery);})}>重新生成安全恢复凭证 <span>→</span></button><button className="management-row danger" disabled={busy} onClick={()=>{if(window.confirm('撤回后立即删除在线回答、联系方式及匹配记录。确认撤回？'))void run(async()=>{await saveNow();draftEnabled.current=false;await api('/api/withdraw','POST',{confirm:true});await refresh();});}}>撤回同意并退出匹配 <span>→</span></button></>}<button className="management-row danger" disabled={busy} onClick={()=>{if(window.confirm('永久删除全部在线个人记录，无法恢复。备份按配置周期失效。确认删除？'))void run(async()=>{draftEnabled.current=false;await chain.current.catch(()=>{});await api('/api/me','DELETE',{confirm:true});setMe(null);setRecovery('');setAnswers({});setStage('deleted');});}}>删除我的个人数据 <span>→</span></button><button className="management-row" disabled={busy} onClick={()=>run(async()=>{await api('/api/logout','POST',{});setMe(null);setRecovery('');setStage('welcome');})}>退出当前浏览器会话 <span>→</span></button></div><button className="text-button" onClick={()=>setStage(me?.user.status==='submitted'?'submitted':me?.user.status==='withdrawn'?'welcome':'form')}>返回</button></section>}
 {stage==='deleted'&&<section className="flow-card narrow success-card"><span className="eyebrow">YOU ARE IN CONTROL</span><h1>数据已删除。</h1><p className="lead">在线个人记录已移除，恢复凭证已失效。备份将按配置的保留周期失效，恢复时需重放删除台账。</p><button className="button primary" onClick={()=>setStage('welcome')}>返回首页 →</button></section>}
 {stage==='privacy'&&meta&&<section className="flow-card"><PrivacyText meta={meta}/><PrivacyText meta={meta} sensitive/><button className="button secondary" onClick={()=>setStage(returnStage)}>返回</button></section>}
 {error&&<div className="error-box" role="alert">{error}{saveState.includes('失败')&&<button className="text-button" onClick={()=>run(async()=>{await saveNow();})}>重试保存</button>}</div>}
 </main><footer className="site-footer"><span>认真认识<span className="footer-note"> · 以认真为开始</span></span><button className="text-button" onClick={()=>{setReturnStage(stage);void run(async()=>{await saveNow();setStage('privacy');});}}>隐私与选择</button><span className="footer-caption">{meta?.icpRecord?<a href="https://beian.miit.gov.cn/" target="_blank" rel="noopener noreferrer">{meta.icpRecord}</a>:'SHANGHAI · PRIVATE BETA'}</span></footer></div>;
}
function format(value:unknown){return Array.isArray(value)?value.join('、'):value===undefined?'未填写':String(value);}
function Recovery({value}:{value:string}){const [copied,setCopied]=useState(false);return <div className="recovery-card"><strong>安全恢复凭证</strong><p>请保存到自己的安全位置。此凭证可访问和删除回答，勿分享或发送给管理员。</p><code>{value}</code><button className="text-button" onClick={()=>{navigator.clipboard?.writeText(value).then(()=>setCopied(true)).catch(()=>setCopied(false));}}>{copied?'已复制':'复制凭证（也可长按保存）'}</button></div>;}
function QuestionInput({question:q,value,onChange}:{question:Question;value:Answers[string]|undefined;onChange:(value:Answers[string]|undefined)=>void}){
 if(q.type==='text')return <textarea aria-label={q.title} value={typeof value==='string'?value:''} maxLength={2000} rows={6} onChange={e=>onChange(e.target.value)} placeholder="慢慢写，想到什么都可以。"/>;
 if(q.type==='scale'&&q.max>5)return <div className="numeric-answer"><label className="sr-only" htmlFor={q.key}>{q.title}</label><input id={q.key} type="number" inputMode="numeric" min={q.min} max={q.max} step={1} value={typeof value==='number'?value:''} onChange={e=>onChange(e.target.value===''?undefined:Number(e.target.value))}/><span>周岁</span></div>;
 if(q.type==='scale')return <><div className="scale-options" role="group" aria-label={q.title}>{Array.from({length:q.max-q.min+1},(_,i)=>i+q.min).map(n=><button key={n} className={value===n?'selected':''} onClick={()=>onChange(n)} aria-pressed={value===n}>{n}</button>)}</div><div className="scale-labels"><span>非常不认同</span><span>非常认同</span></div></>;
 return <div className="choice-list" role="group" aria-label={q.title}>{q.options.map(o=>{const selected=q.type==='multi'?Array.isArray(value)&&value.includes(o.value):value===o.value;return <button key={o.value} className={`choice ${selected?'selected':''}`} aria-pressed={selected} onClick={()=>onChange(q.type==='multi'?(selected?(value as string[]).filter(x=>x!==o.value):[...(Array.isArray(value)?value:[]),o.value]):o.value)}><span>{o.label}</span><span className={`choice-marker ${q.type==='multi'?'square':''}`}>{selected?'✓':''}</span></button>;})}{q.type==='multi'&&<p className="field-hint">可以选择多项。</p>}</div>;
}
